### PR TITLE
Fixed naming format of extractSerpent2GCs.py output files, and pep8'ed

### PR DESCRIPTION
**Pull request by smpark7**
Fixed naming format of data output files to be compatible with Moltres input data file naming requirements. (e.g. betaEff -> BETA_EFF)

Also edited into pep8 format.

### CODE REVIEW

**Comment by smpark7** [comment]
I broke the script. Do not merge yet

**Comment by smpark7** [comment]
Okay, the script is working as it should now.

**Comment by gridley** [comment]
Nice fix! The only thing I'd say that might be good is changing some of the path string lines from ... + '/' + ... to os.path.join, which preserves compatibility with both unix and windows computers. Although, nobody in the right mind would try to run MOOSE on windows, so I'm gonna merge this.

**Comment by lindsayad** [comment]
In the future you can squash fixup commits using 'git commit -a --fixup HEAD' and then 'git rebase -i --autosquash HEAD~2'. This will produce a cleaner history

**Comment by gridley** [comment]
Thanks for the tip Alex! I’ll read into these options some.

**Comment by smpark7** [comment]
Thanks for the tips!

**Pull request merged**
