### PR TITLE
Remove deprecated syntax

### PR DESCRIPTION
**Pull request by aeslaughter**
refs MOOSE #15980

### CODE REVIEW

**Comment by aeslaughter** [comment]
This can be merged now.

**Review by smpark7 — APPROVED** [review]
Thank you. This looks good to me. Seems like your script also corrected a few benign code indent anomalies.

**Comment by aeslaughter** [comment]
> It's weird that the tab syntax eluded previous tests.

I am guessing something was push directly to the devel branch or a PR merged during the two months that testing was down.

**Comment by smpark7** [comment]
> > It's weird that the tab syntax eluded previous tests.
> 
> I am guessing something was push directly to the devel branch or a PR merged during the two months that testing was down.

Ah yes these files are from a fairly recent PR

**Pull request merged**
