### PR TITLE
Move to new Relationship Manager system

### PR DESCRIPTION
**Pull request by lindsayad**
This PR does some various fixups:

- Most importantly: With the new MOOSE ghosting functor system (see idaholab/moose#13145), we have to explicitly add the ghosting we need. If we add an object that needs ghosting through a custom action, we need to ensure that we override the `addRelationshipManagers` method
- Update to the new registry system (includes updating the Squirrel submodule)
- Loosens some tolerances for eigen tests because we've added parallel testing to the CIVET recipe
- Updates the MOOSE submodule so that we have gcc-8 clean module code because we've also added the `-Werror` flag to CIVET
    - rationale for this is that users of Moltres should see clean warning-free output when building Moltres

### CODE REVIEW

**Comment by lindsayad** [comment]
@arfc/current does anyone want to look at this?

**Comment by smpark7** [comment]
I'm currently in transit so I can't run it right now.

The changes in the input file precursor section for the test seem correct.

I'm not familiar with the relationship manager system but I'll look it when I have time later.

**Comment by katyhuff** [comment]
reviewing now.

**Comment by lindsayad** [comment]
Noting that any Moltres input file that has a Precursor action block will not run in parallel with current moose until some of the changes in this PR go in (those in `PrecursorAction.[hC]`).

**Comment by katyhuff** [comment]
bitmoji

**Pull request merged**
