### PR TITLE
Clean up main.C and explicitly register dependent app

### PR DESCRIPTION
**Pull request by MengnanLi91**
Adapt to the new changes in MOOSE(https://github.com/idaholab/moose/pull/25994)

### CODE REVIEW

**Comment by smpark7** [comment]
@MengnanLi91 I think this PR needs to include a MOOSE submodule update to include the changes in idaholab/moose#25994

**Comment by MengnanLi91** [comment]
> @MengnanLi91 I think this PR needs to include a MOOSE submodule update to include the changes in [idaholab/moose#25994](https://github.com/idaholab/moose/pull/25994)

Got it. I can do that. Didn't realize moltres doesn't have auto submodule updates

**Comment by smpark7** [comment]
This is a weird conflict. I don't get a merge conflict message on my local machine when I checked out and merged your branch into devel.

Can you try undoing the moose update commit, updating your Moltres fork, then updating the moose submodule (in that order)? I suspect your commit is somehow conflicting with #255.

**Comment by MengnanLi91** [comment]
> This is a weird conflict. I don't get a merge conflict message on my local machine when I checked out and merged your branch into devel.
> 
> Can you try undoing the moose update commit, updating your Moltres fork, then updating the moose submodule (in that order)? I suspect your commit is somehow conflicting with #255.

Sure, I just rebased my branch. Hopefully it works this time

**Review by smpark7 — APPROVED** [review]

**Pull request merged**
