### PR TITLE
Rodded material done with scalar variables

### PR DESCRIPTION
**Pull request by gridley**
This PR introduces rodded materials to moltres. Control rod regions are governed by a scalar variable called rodPosition. The rodPosition variable gets aligned with either the x, y, or z axes through the rodDimension argument. All material *below* the rodPosition gets assigned a set of properties corresponding to a material property file base name, like the GenericMoltresMaterial. Material *above* rodPosition returns the same set of properties, but instead with removal cross section and removal cross section derivative multiplied by absorb_factor. Absorb_factor can be tuned to match CR worths obtained from experiment or more precise neutronics.

Future work could include altering flux outside the strongly absorbing region in order to mimic transport effects. Other work could involve specifying an arbitrary vector for CR orientation.

PS:

There are some commits that clean out unused property files for the 4 group MSRE case as well.

### CODE REVIEW

**Comment by gridley** [comment]
Merging since it works and Alex is away! :smile:

**Comment by katyhuff** [comment]
RoddedMaterial::computeSplineAbsorbingQpProperties() is a pretty messy function. It may be less error prone code if you split it into smaller, more atomic functions. [http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745)

**Comment by gridley** [comment]
Thanks for the advice. I think it works for now mainly because this is a copied, pasted, and modified version of GenericMoltresMaterial's computeSplineQpProperties. This is a good point, because if we split up the functions in GenericMoltresMateria.l more, RoddedMaterial would be much shorter, probably just overriding two functions (computing the absorption and derivative of absorption cross section).

**Comment by lindsayad** [comment]
Split them up then make a PR

**Pull request merged**
