### PR TITLE
update macros to use new error/warn functions

### PR DESCRIPTION
**Pull request by rwcarlsen**
This is to support an update currently being made to the MOOSE framework.

### CODE REVIEW

**Comment by rwcarlsen** [comment]
FYI - you're master branch that we test against is pretty out of date.

**Comment by lindsayad** [comment]
Yea...the app is in such high development right now that I'm constantly breaking my own integration tests, so I haven't merged into master for a long time because I don't want to disrupt MOOSE tests

**Comment by rwcarlsen** [comment]
That's fine.  What you can do to be ready for these error/warn function related changes as we continue to work through them is to *NOT* use streaming operators inside the error/warning macros.

**Comment by lindsayad** [comment]
Sounds good.

**Pull request merged**
