### PR TITLE
Update deprecated code

### LINKED ISSUE #150: Fixup deprecated code identified by CIVET
This issue can be closed when deprecated MOOSE code and input file syntax [identified by CIVET testing](https://civet.inl.gov/job/674762/) is fixed. This can be checked in Moltres by using the `--error-deprecated` flag when performing local Moltres testing. 

Examples of the errors currently experienced are as follows:

## Deprecated D_name parameter
```
problems/033117_nts_temp_pre_parsed_mat.syntax: *** ERROR ***
problems/033117_nts_temp_pre_parsed_mat.syntax: 
problems/033117_nts_temp_pre_parsed_mat.syntax: 
problems/033117_nts_temp_pre_parsed_mat.syntax: Deprecated code:
problems/033117_nts_temp_pre_parsed_mat.syntax: The parameter D_name is deprecated.
problems/033117_nts_temp_pre_parsed_mat.syntax: This parameter has been renamed to 'diffusivity', which is more mnemonic and more conducive to passing a number literal
```
This also occurs in:
- `problems/2017_annals_pub_msre_compare.2group`
- `problems/2017_annals_pub_msre_compare.4group`
- `temp.temp`
- `problems/2017_annals_pub_msre_compare.auto_diff_rho`

## Changed addVariable API 

See [this MOOSE newsletter](https://mooseframework.inl.gov/newsletter/2019_08.html) and idaholab/moose#13769 for more info, and idaholab/moose#14061 for some module fixup examples that may prove useful (specifically [this commit](https://github.com/idaholab/moose/commit/b0d160c17f568ea78b96bbf985841cb0998401bc))

```
diracHX.dirachx: *** ERROR ***
diracHX.dirachx: 
diracHX.dirachx: 
diracHX.dirachx: Deprecated code:
diracHX.dirachx: Please use the addVariable(var_type, var_name, params) API instead
```
This also occurs in:
- `pre.pre`
- `nts.nts`
- `problems/2017_annals_pub_msre_compare.2group_eigen`
- `problems/2017_annals_pub_msre_compare.4group_eigen`

---
@katyhuff Apologies if I missed the mark on your preferred issue template! I took at look at CONTRIBUTING, but didn't see anything on issue creation.

### PR DESCRIPTION
**Pull request by robfairh**
Fixes #150.

Running ```./run_tests -j4 --error-deprecated``` yields the following output:

```bash
pre.pre_loop_ins ................................................................................ [HEAVY] SKIP
pre.pre_loop .................................................................................... [HEAVY] SKIP
twod_axi_coupled.coupled ........................................................................ [HEAVY] SKIP
pre.pre ................................................................................................... OK
temp.temp ................................................................................................. OK
decay_heat.decay_heat ..................................................................................... OK
laminar_flow.boussinesqSquare ............................................................................. OK
bcs.coupled_bc ............................................................................................ OK
kernels.scalar_advection_art_diff ......................................................................... OK
postprocessors.side_weighted_integral ..................................................................... OK
nts.nts ................................................................................................... OK
problems/2017_annals_pub_msre_compare.4group ..................................................... SYNTAX PASS
postprocessors.side_weighted_integral_RZ .................................................................. OK
problems/2017_annals_pub_msre_compare.4group_eigen ............................................... SYNTAX PASS
problems/2017_annals_pub_msre_compare.2group ..................................................... SYNTAX PASS
problems/2017_annals_pub_msre_compare.2group_eigen ............................................... SYNTAX PASS
nts.nts_no_action ......................................................................................... OK
diracHX.dirachx ........................................................................................... OK
problems/2017_annals_pub_msre_compare.auto_diff_rho .............................................. SYNTAX PASS
problems/033117_nts_temp_pre_parsed_mat.syntax ....................................................... RUNNING
problems/033117_nts_temp_pre_parsed_mat.syntax ........................................ [FINISHED] SYNTAX PASS
--------------------------------------------------------------------------------------------------------------
Ran 17 tests in 131.0 seconds.
17 passed, 3 skipped, 0 pending, 0 failed

```

Some of the files where I changed `D_name` by `diffusivity` are not included in the tests, but I updated them anyway to be consistent.

### CODE REVIEW

**Comment by robfairh** [comment]
I have also run ```./run_tests -j4 --heavy``` and the output is the following:

```bash
pre.pre_loop ......................................................................................... RUNNING
twod_axi_coupled.coupled ............................................................................. RUNNING
pre.pre_loop ................................................................................... [FINISHED] OK
pre.pre_loop_ins ..................................................................................... RUNNING
twod_axi_coupled.coupled ....................................................................... [FINISHED] OK
pre.pre_loop_ins ............................................................................... [FINISHED] OK
--------------------------------------------------------------------------------------------------------------
Ran 3 tests in 186.7 seconds.
3 passed, 0 skipped, 0 pending, 0 failed
```

I guess this partially solves #152.
Maybe removing [these](https://github.com/arfc/moltres/blob/devel/tests/pre/tests#L11) lines would finish solving it? @smpark7 thoughts?

**Comment by robfairh** [comment]
Well, it seems like the tests pass on CIVET now. The error comes on the unit tests.

**Review by smpark7 — COMMENTED** [review]
Looks good! I think you've resolved everything in #150.

Yea the heavy tests still fail with the latest moose build because of the changes in MultiAppPostprocessorTransfer. As for the unit test build failing, it should be fixed once #155 is merged. I'll approve this when the tests pass after #155 is merged into devel and you've merged that into this branch.

**Comment by robfairh** [comment]
@smpark7 Done!

**Review by smpark7 — APPROVED** [review]

**Pull request merged**
