### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by StoneCypher**
the oxford comma matters

### CODE REVIEW

**Comment by lindsayad** [comment]
The Oxford comma is for three or more terms; there are only two terms in that sentence. Pull requests without stripper memes would be much more appreciated.

**Comment by StoneCypher** [comment]
"The Oxford comma is for three or more terms"

Actual Oxford seems to disagree.  The difference between the serial comma and the Oxford comma is that what you just described is the serial comma.

I apologize that I tried to add a funny joke to lighten the mood while explaining.

I won't bother with further pull requests after the tone of this response.

**Comment by lindsayad** [comment]
I don't like to discourage contribution. But could you potentially see that an initial pull request without any prior communication that leads with a meme like that might be met with skepticism? You may very well be right about the distinction between an Oxford and serial comma. However, Wikipedia redirects searches for "Oxford comma" to "serial comma" and describes the two as synonyms. I'm not saying that Wikipedia is the Bible for grammar, hence why I'm willing to concede that you may be correct in which case there seems to be very widespread public misconception of what the Oxford comma is. If you link me to a good dictionary reference, I will merge your PR.

**Comment by StoneCypher** [comment]
> But could you potentially see that an initial pull request without any prior communication that leads with a meme like that might be met with skepticism? 

Could I see how fixing an Oxford comma, along with a cartoon pointing out what the difference is, might be met with skepticism?

No.  

.

>  If you link me to a good dictionary reference, I will merge your PR.

Dictionaries don't cover things like this.

I already deleted the branch, because your reaction to a mild explanatory cartoon (which is not in any way a meme) sort of annoys me.  

I apologize for trying to help.  I've also deleted the code I was writing for you.

Please have a good day.

**Pull request closed without merging**
