### PR TITLE
Update to new MOOSE JSON package

### PR DESCRIPTION
**Pull request by aeslaughter**
Updates for coming changes to MOOSE. This will fail until those changes are merged, see [MOOSE#15719](https://github.com/idaholab/moose/pull/15710)

(refs [MOOSE#11323](https://github.com/idaholab/moose/issues/11323))

### CODE REVIEW

**Review by katyhuff — APPROVED** [review]
Thanks @aeslaughter . This looks good to me. @smpark7 can you think of anything else in the codebase that this might impact?

**Comment by aeslaughter** [comment]
@katyhuff I think my original comment was unclear. With this being merged moltres no longer will compile, until [MOOSE#15719](https://github.com/idaholab/moose/pull/15710) is merged. I am hoping that happens soon, but can't be for sure. You might want to revert this merge for the time being. Sorry for the confusion.

**Comment by katyhuff** [comment]
Ah! Thanks!!
Your comment was clear -- that was how I understood it originally. But, then I noticed that in the CI, Moltres was the only app failing the tests and doubted myself!  Reverting. 
Now I have something else about those failing tests to figure out...

**Comment by katyhuff** [comment]
I'll keep an eye on MOOSE#15719  and will revert the revert at that time. Sorry!

**Pull request merged**
