### PR TITLE
PR and Issue templates

### LINKED ISSUE #130: Create templates for issues and pull requests
EDIT 1: The first comment below strongly discourages an entire new document be created for contributing and suggests using GitHub templates instead along with editing he CONTRIBUTING.md document. I agree this is a much more efficient approach. The issue has been updated to reflect this.

Moltres development could be improved by adding templates for issues and pull requests. The existence of these templates can be noted in the CONTRIBUTING.md document.

This issue can be closed when templates for issues and pull requests exist, and the existence of these templates is specified in the CONTRIBUTING.md document.

Original issue preserved below
-----------------------------
Original Title: Create a Contributing Guide

Moltres does not have a Contributing Guide. A Contributing Guide defines the appropriate procedure for making contributions to a project. A contributing guide is important for open source projects like Moltres to ensure that code issues are dealt with appropriately and efficiently.

The Contributing Guide should specify

 - steps for submitting a bug report/feature request/other misc. project thingy and the expected structure of such a report/request/thingy
 - steps for reviewing a bug report/feature request/other misc. project thingy and the expected structure of such a review of said report/request/thingy

Many of these items already exist in the [current CONTRIBUTING.md document](https://github.com/arfc/moltres/blob/devel/CONTRIBUTING.md).

This list is not comprehensive and should be updated as necessary. The Contributing Guide should use clear, concise, and easy to read language. A good place to start for inspiration might be the [ARFC Guides](http://arfc.github.io/manual/guides/) or the [OpenMC contributing guide](https://docs.openmc.org/en/latest/devguide/contributing.html)

This issue can be closed once a Contributing guide that addresses the above items exists.

### PR DESCRIPTION
**Pull request by yardasol**
This PR adds PR and Issue templates to the repo. They are similar to the ones i made for SaltProc but with some better formatting.

closes #130

### CODE REVIEW

**Comment by yardasol** [comment]
@katyhuff @smpark7 bump

**Comment by smpark7** [comment]
(Meta question) Do we want the templates to be strictly followed or to be general guidelines? I recognize the benefits of standardization since we welcome outside contributors, but I find the headers in the issue templates to be quite restrictive. I would prefer to have `Expected behavior`, `Describe the bug`, and `To reproduce` be guidelines under one big section named `Description`.

As for the PR template, I think the checklist is good for reminding contributors (and ourselves) of our expectations.

**Comment by yardasol** [comment]
@smpark7 great suggestions. Could you go ahead and suggest those changes so you can get commit credit for them?

**Review by katyhuff — APPROVED** [review]
This looks like a good addition. I have no problem with them as written. I see @smpark7 has made a suggestion and @yardasol has suggested that @smpark7 implement those suggested changes. For expediency, I recommend either the original PR author @yardasol  incorporate those recommendations OR merging as is and allowing @smpark7 to make a separate PR with those changes sometime later.

**Comment by katyhuff** [comment]
@yardasol @smpark7 Can you take a quick look at my final comment and decide what to do with this PR?

**Comment by smpark7** [comment]
I'm okay with merging as is and refining the template later.

**Comment by katyhuff** [comment]
Thank you. Merged.

**Pull request merged**
